"""initial

Revision ID: 001
Revises: 
Create Date: 2026-07-04 13:22:17.583777
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('trim', sa.String(length=200), nullable=True),
    sa.Column('body_style', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('nhtsa_vin', sa.String(length=17), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make', 'model', 'year')
    )
    op.create_index(op.f('ix_cars_make'), 'cars', ['make'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_year'), 'cars', ['year'], unique=False)
    op.create_table('design_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('body_style', sa.String(length=50), nullable=False),
    sa.Column('scale', sa.String(length=20), nullable=False),
    sa.Column('parts_count', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('template_ldr', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('adjustable_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_templates_body_style'), 'design_templates', ['body_style'], unique=False)
    op.create_table('lego_sets',
    sa.Column('set_num', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('brick_count', sa.Integer(), nullable=True),
    sa.Column('car_make', sa.String(length=100), nullable=True),
    sa.Column('car_model', sa.String(length=200), nullable=True),
    sa.Column('minifigs', sa.Integer(), nullable=True),
    sa.Column('rebrickable_id', sa.String(length=20), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('instructions_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('set_num')
    )
    op.create_index(op.f('ix_lego_sets_car_make'), 'lego_sets', ['car_make'], unique=False)
    op.create_index(op.f('ix_lego_sets_car_model'), 'lego_sets', ['car_model'], unique=False)
    op.create_table('mocs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rebrickable_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('car_make', sa.String(length=100), nullable=True),
    sa.Column('car_model', sa.String(length=200), nullable=True),
    sa.Column('parts_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('ldraw_file', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mocs_car_make'), 'mocs', ['car_make'], unique=False)
    op.create_index(op.f('ix_mocs_car_model'), 'mocs', ['car_model'], unique=False)
    op.create_table('part_colors',
    sa.Column('part_num', sa.String(length=25), nullable=False),
    sa.Column('ldraw_color_id', sa.SmallInteger(), nullable=False),
    sa.Column('lego_element_id', sa.String(length=10), nullable=True),
    sa.Column('bricklink_color_id', sa.SmallInteger(), nullable=True),
    sa.Column('bricklink_part_id', sa.String(length=20), nullable=True),
    sa.Column('rebrickable_color_id', sa.SmallInteger(), nullable=True),
    sa.Column('color_name', sa.String(length=50), nullable=True),
    sa.Column('hex_rgb', sa.String(length=7), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('part_num', 'ldraw_color_id')
    )
    op.create_table('parts',
    sa.Column('part_num', sa.String(length=25), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ldraw_name', sa.String(length=25), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('brick_type', sa.String(length=30), nullable=True),
    sa.Column('dimensions_mm', sa.JSON(), nullable=True),
    sa.Column('year_released', sa.SmallInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('part_num')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.String(length=30), nullable=True),
    sa.Column('auth_id', sa.String(length=255), nullable=True),
    sa.Column('saved_designs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('designs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True, comment='Owner (Phase 2)'),
    sa.Column('match_level', sa.SmallInteger(), nullable=False, comment='1=official set, 2=MOC, 3=template, 4=AI'),
    sa.Column('matched_set_num', sa.String(length=20), nullable=True),
    sa.Column('matched_moc_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending / processing / completed / failed'),
    sa.Column('scale', sa.String(length=30), nullable=True, comment='minifig-scale / speed-champions / technic / creator-expert'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='private / public / unlisted'),
    sa.Column('parts_count', sa.Integer(), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('file_io_path', sa.Text(), nullable=True),
    sa.Column('file_pdf_path', sa.Text(), nullable=True),
    sa.Column('file_ldr_path', sa.Text(), nullable=True),
    sa.Column('ai_job_id', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parent_design_id', sa.Uuid(), nullable=True, comment='If this is a customization, references the base design'),
    sa.Column('customization_request', sa.Text(), nullable=True, comment="The user's customization instructions"),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['matched_moc_id'], ['mocs.id'], ),
    sa.ForeignKeyConstraint(['matched_set_num'], ['lego_sets.set_num'], ),
    sa.ForeignKeyConstraint(['parent_design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['design_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('design_id', sa.Uuid(), nullable=False),
    sa.Column('part_num', sa.String(length=25), nullable=False),
    sa.Column('ldraw_color_id', sa.SmallInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('bricklink_id', sa.String(length=20), nullable=True),
    sa.Column('bricklink_color_id', sa.SmallInteger(), nullable=True),
    sa.Column('price_guide', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_num'], ['parts.part_num'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'part_num', 'ldraw_color_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_parts')
    op.drop_table('designs')
    op.drop_table('users')
    op.drop_table('parts')
    op.drop_table('part_colors')
    op.drop_index(op.f('ix_mocs_car_model'), table_name='mocs')
    op.drop_index(op.f('ix_mocs_car_make'), table_name='mocs')
    op.drop_table('mocs')
    op.drop_index(op.f('ix_lego_sets_car_model'), table_name='lego_sets')
    op.drop_index(op.f('ix_lego_sets_car_make'), table_name='lego_sets')
    op.drop_table('lego_sets')
    op.drop_index(op.f('ix_design_templates_body_style'), table_name='design_templates')
    op.drop_table('design_templates')
    op.drop_index(op.f('ix_cars_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_make'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
